spring.application.name=ImpactTracking
server.port=8082


foodlisting.service.url=http://localhost:8081/api/foodlist

points.per-submission=10
points.complete-bonus=10

badge.bronze=100
badge.silver=200
badge.gold=500

badge.bronze-saver=10
badge.silver-saver=25
badge.gold-saver=50
badge.community-hero=100

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
